---
- name: Download latest version
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: "{{ global_cache_dir | mandatory }}/"
  become: false
  delegate_to: localhost

- name: Create root
  file: 
    path: "{{nextcloud_path}}"
    state: directory 
    mode: 0755
    owner: www-data

- name: Extract nextcloud into install path
  unarchive:
    src: "{{ global_cache_dir }}/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: "{{ nextcloud_path }}/"
    remote_src: True
    owner: www-data
    group: www-data
  creates: "{{ mattermost_mattermail_install_path }}/mattermail"

- name: Create a new database with name '{{ nextcloud_mysql_database_name }}'
  mysql_db:
    name: "{{ nextcloud_mysql_database_name }}"
    state: present

- name: Create mariadb user
  mysql_user:
    name: "{{ nextcloud_mysql_user }}"
    password: "{{ nextcloud_mysql_password }}"
    priv: '{{ nextcloud_mysql_database_name }}.*:ALL,GRANT'
    state: present

- name: Run the nextcloud installer from command line using sudo since become is shitty
  shell: sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "{{nextcloud_mysql_database_name}}"  --database-user "{{nextcloud_mysql_user}}" --database-pass "{{nextcloud_mysql_password}}" --admin-user "{{ nextcloud_user }}" --admin-pass "{{ nextcloud_password }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Add the domain to the trusted domains
  shell: "sudo -u www-data php occ config:system:set trusted_domains {{ item.0 }} --value={{ item.1 }}"
  with_indexed_items: "{{ nextcloud_trusted_domains }}"
  args:
    chdir: "{{ nextcloud_path }}"

- import_tasks: ldap.yml

