---
- name: Download latest version
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: "{{ global_cache_dir | mandatory }}/"
  become: false
  delegate_to: localhost


- name: Extract Nextcloud into tmp dir
  unarchive:
    src: "{{ global_cache_dir }}/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/tmp"
    owner: www-data
    group: www-data

- name: Copy Nextcloud from tmp dir to install dir
  command: "mv -f /tmp/nextcloud {{ nextcloud_path }}"

- name: Set permissions on root
  file: 
    path: "{{ nextcloud_path }}"
    state: directory 
    mode: 0755
    owner: www-data

- name: Create a new database with name '{{ nextcloud_mysql_database_name }}'
  mysql_db:
    name: "{{ nextcloud_mysql_database_name }}"
    state: present

- name: Create mariadb user
  mysql_user:
    name: "{{ nextcloud_mysql_user }}"
    password: "{{ nextcloud_mysql_password }}"
    priv: '{{ nextcloud_mysql_database_name }}.*:ALL,GRANT'
    state: present

- name: Run the nextcloud installer from command line
  shell: sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "{{nextcloud_mysql_database_name}}"  --database-user "{{nextcloud_mysql_user}}" --database-pass "{{nextcloud_mysql_password}}" --admin-user "{{ nextcloud_user }}" --admin-pass "{{ nextcloud_password }}"
  args:
    chdir: "{{ nextcloud_path }}/"

- import_tasks: ldap.yml

