---
- name: Enable the ldap plugin from command line using sudo since become is shitty
  shell: sudo -u www-data php occ app:enable user_ldap
  args:
    chdir: "{{ nextcloud_path }}"

- name: Create empty ldap config
  shell: sudo -u www-data php occ ldap:create-empty-config
  args:
    chdir: "{{ nextcloud_path }}"
  register: config_id_output

- set_fact:
    config_id: "{{ config_id_output['stdout'].split(' ') | last}}"

- name: Set ldapAgentName
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapAgentName {{ldapAgentName}}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapAgentPassword
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapAgentPassword {{ldapAgentPassword}}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapBase
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapBase {{ldapBase}}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapBaseGroups
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapBaseGroups {{ldapBaseGroups}}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapBaseUsers
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapBaseUsers '{{ldapBaseUsers}}'"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapConfigurationActive  
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapConfigurationActive 1"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapGroupFilter 
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapGroupFilter '{{ ldapGroupFilter }}'"
  args:
    chdir: "{{ nextcloud_path }}"

- name: ldapGroupFilterObjectclass
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapGroupFilterObjectclass {{ ldapGroupFilterObjectclass }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapGroupMemberAssocAttr 
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapGroupMemberAssocAttr {{ ldapGroupMemberAssocAttr }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapHost 
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapHost {{ ldapHost }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapLoginFilter
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapLoginFilter '{{ ldapLoginFilter }}'"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapUserDisplayName
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapUserDisplayName {{ ldapUserDisplayName }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapUserFilter
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapUserFilter '{{ ldapUserFilter }}'"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapUserFilterObjectclass
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapUserFilterObjectclass '{{ ldapUserFilterObjectclass }}'"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldaphasMemberOfFilterSupport
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} hasMemberOfFilterSupport   '{{ ldaphasMemberOfFilterSupport }}'"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapPort
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapPort {{ ldapPort }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Set ldapEmailAttribute
  shell: "sudo -u www-data php occ ldap:set-config {{ config_id }} ldapEmailAttribute {{ ldapEmailAttribute }}"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Test ldap plugin config
  shell: "sudo -u www-data php occ ldap:test-config {{ config_id }}"
  args:
    chdir: "{{ nextcloud_path }}"
  register: valid_config

- fail:
    msg: "The configuration is invalid. Please have a look at the logs for further details."
  when: valid_config['stdout'] != "The configuration is valid and the connection could be established!"
